name: OSMesa Windows Library Builder
run-name: Build OSMesa for Windows by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  MESA_VERSION: 24.3.3

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ runner.arch }}
        vsversion: 2019
        
    - name: download mesa source
      run: |
        Invoke-WebRequest https://archive.mesa3d.org/mesa-${{ env.MESA_VERSION }}.tar.xz -OutFile mesa-${{ env.MESA_VERSION }}.tar.xz        
        dir
        
    - name: unzip mesa source
      run: |
        7z x mesa-${{ env.MESA_VERSION }}.tar.xz -omesa
        dir mesa

    - name: unpack mesa source
      run: |
        7z x mesa/mesa-${{ env.MESA_VERSION }}.tar -omesa_src
        dir mesa_src
        move mesa_src/mesa-${{ env.MESA_VERSION }} .
        
    - name: prereqs
      run: choco install winflexbison pkgconfiglite ninja

      
    - name: install meson
      run: python3 -m pip install meson packaging mako PyYAML
      
    - name: build
      working-directory: mesa-${{ env.MESA_VERSION }}
      run: |
        meson setup builddir -Dosmesa=true -Dgallium-drivers=softpipe -Dvulkan-drivers="[]" -Dprefix="$PWD/../osmesa" --backend=vs
        meson compile -C builddir
        meson install -C builddir
            
    # - name: Add MSBuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.2

    # - name: Restore NuGet packages
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    # - name: Build
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   # Add additional options to the MSBuild command line here (like platform or verbosity level).
    #   # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
    #   run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    # - name: get_source
